### ISSUE TITLE
Potential date bug

### ISSUE THREAD

**Issue by ivank** [ValeriMladenov/Faibler-Backend#4]
Awesome project. I think I might have found a small bug though - wouldn't the date be cached and subsequent executions use the cached date?

https://github.com/ValeriMladenov/Faibler-Backend/blob/cc1bea26bc299dbc138d14eb4c19e33584a8d70b/util/mails/sendReport.js#L3-L4

Apologies if this is not the case!

**Comment by ValeriMladenov** [comment]
Thanks! :)
